server:
  port: 8091

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 100
        format_sql: true
    open-in-view: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(ulGy/5rB4Y7rD0wHbwR21rLG/jT1Lkm02LgSbHuE9n9mmxZmv0FenoE8dD89qMadlLdy+gAf24ulHM3z9/JYrQ==)
    username: ENC(gv8+vDAseDkw87FNUNmFQVdk5dTBu0GQ71VBBuUyeIY=)
    password: ENC(VcPYkEOg9OzuwNw1UeYOgLqKsRkFoRUHwjRcxZzGgZQ=)
    hikari:
      maximum-pool-size: 100
      idle-timeout: 20000
      validation-timeout: 5000
      minimum-idle: 5


logging:
  file:
    path: ./logs/batch/
    name: batch-log
  logback:
    rolling policy:
      max-history: 14
      max-file-size: 50MB
      total-size-cap: 5GB
  level:
    root: warn
    com.kernel360: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace
    org:
      springframework:
        transaction=DEBUG:











