name: Java CI with Gradle WashPedia Project

on:
  push:
    branches: [ "send_develop_server" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Replace SQL Queries
        run: |
          sql_directory="./module-api/src/main/resources/db/migration"
          old_text="changeRequired"
          new_text="${{ secrets.PUBLIC_KEY }}"
          find "$sql_directory" -type f -name "*.sql" -exec sed -i "s|$old_text|$new_text|g" {} +

      - name: Grant execute permission for gradlew
        working-directory: ./module-api
        run: chmod +x ./gradlew

      - name: Build with Gradle
        working-directory: ./module-api
        run: ./gradlew build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Copy JAR file to remote server using SCP
        run: |
          cd module-api/build/libs/
          export PASSWORD="${{ secrets.VULTR_PW }}"
          sshpass -p "$PASSWORD" scp -o StrictHostKeyChecking=no -P 22 module-api-0.0.1-SNAPSHOT.jar ${{ secrets.VULTR_USER_NAME }}@${{ secrets.VULTR_IP }}:/root

      ## 터미널 접속 후 실행 -> 수정 필요
      - name: Application Run on Remote Server
        run: |
          export JAR_NAME="module-api-0.0.1-SNAPSHOT.jar"
          export PASSWORD="${{ secrets.VULTR_PW }}"
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no ${{ secrets.VULTR_USER_NAME }}@${{ secrets.VULTR_IP }} \
          "pgrep -f java | xargs kill -9 && \
          cd \$HOME && \
          echo pwd && \
          mkdir -p ./logs && \
          nohup java -jar $JAR_NAME --jasypt.encryptor.password=${{ secrets.PUBLIC_KEY }} >> ./logs/deploy_success.log 2> ./logs/deploy_error.log & "